# Change these first
owner: gcommeuneidee # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: AuPetit IP
    url: $AUPETIT_IP
  - name: Barraco
    url: $BARRACO
  - name: Beemotion
    url: $BEEMOTION
  - name: Burotic
    url: $BUROTIC
  - name: Chasseur sous-marin
    url: $CHASSEUR_SOUS_MARIN
  - name: Convergens
    url: $CONVERGENS
  - name: Domaine de Poulaines
    url: $DOMAINE_POULAINES
  - name: G comme une idée
    url: $G_COMME_UNE_IDEE
  - name: Gardon Mollard
    url: $GARDON_MOLLARD
  - name: Gedo Permanence
    url: $GEDO_PERMANENCE
  - name: Laiterie de Verneuil
    url: $LAITERIE_VERNEUIL
  - name: Martin Fraudreau
    url: $MARTIN_FRAUDREAU
  - name: Orgasoftware
    url: $ORGASOFTWARE
  - name: Phone Services
    url: $PHONE_SERVICES
  - name: RDV Internet
    url: $RDVINTERNET
  - name: Rotowash
    url: $ROTOWASH
  - name: Saint-Ouen-les-Vignes
    url: $SAINT_OUEN_LES_VIGNES
  - name: Sennegon
    url: $SENNEGON
  - name: Tours Métropole Basket
    url: $TOURS_METROPOLE_BASKET
  - name: Weser
    url: $WESER
  - name: Yona Design
    url: $YONA_DESIGN

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://www.gcommeuneidee.com/wp-content/themes/gcommeuneidee/svg/logo.svg
  name: G comme une idée
  introTitle: "Moniteur de disponibilité et page de statut utilisant **Upptime**."
  introMessage: "Il s'agit d'une page de statut qui utilise des données **en temps réel** de notre [référenciel](https://github.com/gcommeuneidee/upptime)."
  navbar:
    - title: Status
      href: /upptime

i18n:
  activeIncidents: Incidents en cours
