# Change these first
owner: gcommeuneidee # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: AuPetit IP
    url: https://aupetitip.fr
  - name: Barraco
    url: https://www.barraco-construction.com
  - name: Beemotion
    url: https://www.beemotion.eu
  - name: Burotic
    url: https://www.burotic.fr
  - name: Chasseur sous-marin
    url: https://www.lechasseursousmarin.com
  - name: Convergens
    url: https://www.convergens-avocats.fr
  - name: Domaine de Poulaines
    url: https://www.domaine-poulaines.com
  - name: G comme une idée
    url: https://www.gcommeuneidee.com
  - name: Gardon Mollard
    url: https://gardon-mollard-guillaume.chirurgiens-dentistes.fr
  - name: Laiterie de Verneuil
    url: https://laiterie-de-verneuil.com
  - name: Martin Fraudreau
    url: https://www.martinfraudreau.com
  - name: Orgasoftware
    url: https://orgasoftware.com
  - name: Phone Services
    url: https://phone-services.fr
  - name: RDV Internet
    url: https://www.rdvinternet.fr
  - name: Rotowash
    url: https://rotowash.fr
  - name: Saint-Ouen-les-Vignes
    url: https://www.saint-ouen-les-vignes.fr
  - name: Sennegon
    url: https://www.sennegon.com
  - name: Tours Métropole Basket
    url: https://toursmetropolebasket.com
  - name: Weser
    url: https://weser.fr
  - name: Yona Design
    url: https://www.yona-design.com
  - name: Test notification
    url: https://www.google.fr

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /upptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
