# Change these first
owner: gcommeuneidee # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Académie de la Truffe
    url : $ACADEMIE_TRUFFE
    __dangerous__body_down_if_text_missing: 'Académie de la Truffe'
  - name: Agence CMS
    url: $AGENCE_CMS
    __dangerous__body_down_if_text_missing: 'Agence CMS'
  - name: ARAPI Autisme
    url: $ARAPI_SITE
    __dangerous__body_down_if_text_missing: 'ARAPI Autisme'
  - name: ARAPI Gestion
    url: $ARAPI_GESTION
    __dangerous__body_down_if_text_missing: 'Identifiant'
  - name: ARAPI Université
    url: $ARAPI_UA
    __dangerous__body_down_if_text_missing: 'ARAPI Université'
  - name: AuPetit IP
    url: $AUPETIT_IP
    __dangerous__body_down_if_text_missing: 'AUPETIT IP'
  - name: Alterpaint
    url: $ALTERPAINT
    __dangerous__body_down_if_text_missing: 'Alterpaint'
  - name: Aventa
    url: $AVENTA
    __dangerous__body_down_if_text_missing: 'Aventa'
  - name: Barraco
    url: $BARRACO
    __dangerous__body_down_if_text_missing: 'Barraco'
  - name: Beemotion
    url: $BEEMOTION
    __dangerous__body_down_if_text_missing: 'Beemotion'
  - name: Bureau21
    url: $BUREAU_21
    __dangerous__body_down_if_text_missing: 'Bureau 21'
  - name: Cangey
    url: $CANGEY
    __dangerous__body_down_if_text_missing: 'Cangey'
  - name: Céline da Graça Pires
    url: $CELINE_PIRES
    __dangerous__body_down_if_text_missing: 'Collaborate'
  - name: Chasseur sous-marin
    url: $CHASSEUR_SOUS_MARIN
    __dangerous__body_down_if_text_missing: 'sous-marine'
  - name: Convergens
    url: $CONVERGENS
    __dangerous__body_down_if_text_missing: 'Accueil - Convergens'
  - name: Copelva
    url: $COPELVA
    __dangerous__body_down_if_text_missing: 'Copelva'
  - name: Degrav'Agri
    url: $DEGRAV_AGRI
    __dangerous__body_down_if_text_missing: 'Degrav&#039;Agri'
  - name: Devin Collection
    url: $DEVIN_COLLECTION
    __dangerous__body_down_if_text_missing: 'Devin Collection'
  - name: Domaine de Poulaines
    url: $DOMAINE_POULAINES
    __dangerous__body_down_if_text_missing: 'Domaine de Poulaines'
  - name: G comme une idée
    url: $G_COMME_UNE_IDEE
    __dangerous__body_down_if_text_missing: 'G comme une idée'
  - name: Gardon Mollard
    url: $GARDON_MOLLARD
    __dangerous__body_down_if_text_missing: 'Gardon-Mollard'
  - name: Gedo Permanence
    url: $GEDO_PERMANENCE
    __dangerous__body_down_if_text_missing: 'Gedo Permanence'
  - name: Geocean
    url: $GEOCEAN
    __dangerous__body_down_if_text_missing: 'Geocean'
  - name: HandiMobile37
    url: $HANDIMOBILE
    __dangerous__body_down_if_text_missing: 'Handi Mobile'
  - name: Inovamed
    url: $INOVAMED
    __dangerous__body_down_if_text_missing: 'Inovamed'
  - name: Kanyon Consulting
    url: $KANYON_CONSULTING
    __dangerous__body_down_if_text_missing: 'Kanyon Consulting'
  - name: Kraken Subsea
    url: $KRAKEN
    __dangerous__body_down_if_text_missing: 'Kraken'
  - name: Laiterie de Verneuil
    url: $LAITERIE_VERNEUIL
    __dangerous__body_down_if_text_missing: 'Laiterie Verneuil'
  - name: Leggerini Gravure
    url: $LEGGERINI_GRAVURE
    __dangerous__body_down_if_text_missing: 'Leggerini'
  - name: Nerio
    url: $NERIO
    __dangerous__body_down_if_text_missing: 'Nerio'
  - name: Nudjy
    url: $NUDJY
    __dangerous__body_down_if_text_missing: 'Nudjy'
  - name: Numaterra
    url: $NUMATERRA
    __dangerous__body_down_if_text_missing: 'Numaterra'
  - name: PAM Conseil
    url: $PAM_CONSEIL
    __dangerous__body_down_if_text_missing: 'PAM Conseil'
  - name: RDV Internet
    url: $RDVINTERNET
    __dangerous__body_down_if_text_missing: 'RDV Internet'
  - name: Resallience
    url: $RESALLIENCE
    __dangerous__body_down_if_text_missing: 'Resallience'
  - name: Restaurant Les Jardiniers
    url: $RESTAURANT_LES_JARDINIERS
    __dangerous__body_down_if_text_missing: 'Les Jardiniers'
  - name: Saint-Ouen-les-Vignes
    url: $SAINT_OUEN_LES_VIGNES
    __dangerous__body_down_if_text_missing: 'Saint-Ouen-les-Vignes'
  - name: Socom Comparateur
    url: $SOCOM_COMPARATEUR
    __dangerous__body_down_if_text_missing: 'Lecomparateur'
  - name: Tours Métropole Basket PLL
    url: $TOURS_METROPOLE_BASKET_PLL
    __dangerous__body_down_if_text_missing: 'Tours Métropole Basket'
  - name: Weser
    url: $WESER
    __dangerous__body_down_if_text_missing: 'Weser'
  - name: Yona Design
    url: $YONA_DESIGN
    __dangerous__body_down_if_text_missing: 'Yona Design'

status-website:
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/gcommeuneidee/upptime/master/assets/apple-touch-icon.png
  name: G comme une idée
  introTitle: "Moniteur de disponibilité et page de statut utilisant **Upptime**."
  introMessage: "Il s'agit d'une page de statut qui utilise des données **en temps réel** de notre [référenciel](https://github.com/gcommeuneidee/upptime)."
  navbar:
    - title: Statut
      href: /upptime

i18n:
  activeIncidents: Incidents en cours
  allSystemsOperational: Tous les systèmes sont opérationnels
  incidentReport: "Rapport d'incident #$NUMBER →"
  activeIncidentSummary: Ouvert le $DATE avec $POSTS commentaires
  incidentTitle: "Détails de l'incident $NUMBER"
  incidentDetails: "Détails de l'incident"
  incidentFixed: Corrigé
  incidentOngoing: En cours
  incidentOpenedAt: Ouvert le
  incidentClosedAt: Fermé le
  incidentViewOnGitHub: "Voir et s'abonner sur GitHub"
  incidentCommentSummary: Publié le $DATE par $AUTHOR
  incidentBack: ← Retour à tous les incidents
  pastIncidents: Incidents passés
  pastIncidentsResolved: Résolu en $MINUTES minutes avec $POSTS commentaires
  liveStatus: Statut actuel
  overallUptime: "Disponibilité globale : $UPTIME"
  overallUptimeTitle: Disponibilité globale
  averageResponseTime: "Temps de réponse moyen : $TIMEms"
  averageResponseTimeTitle: Réponse moyenne
  sevelDayResponseTime: Temps de réponse sur 7 jours
  responseTimeMs: Temps de réponse (ms)
  up: En ligne
  down: Hors ligne
  degraded: Dégradé
  ms: ms
  loading: Chargement
  navGitHub: GitHub
  footer: cette page est [open-source]($REPO), propulsée par [Upptime](https://upptime.js.org)
  rateLimitExceededTitle: Limite de requête dépassée
  rateLimitExceededIntro: "Vous avez dépassé le nombre de requêtes que vous pouvez faire en une heure, vous devrez donc attendre avant d'accéder à nouveau à ce site Web. Alternativement, vous pouvez ajouter un Jeton d'Accès Personnel GitHub pour continuer à utiliser ce site Web."
  rateLimitExceededWhatDoesErrorMean: Que signifie cette erreur ?
  rateLimitExceededErrorMeaning: "Ce site Web utilise l'API GitHub pour accéder à des données en temps réel sur le statut de nos sites Web. Par défaut, GitHub autorise 60 requêtes par heure par adresse IP, que vous avez consommées."
  rateLimitExceededErrorHowCanFix: Comment puis-je résoudre ce problème ?
  rateLimitExceededErrorFix: "Vous pouvez attendre encore une heure et la limite de votre adresse IP sera restaurée. Alternativement, vous pouvez ajouter votre Jeton d'Accès Personnel GitHub, ce qui vous donne 5 000 requêtes supplémentaires par heure."
  rateLimitExceededGeneratePAT: "Apprenez à générer un Jeton d'Accès Personnel"
  rateLimitExceededHasSet: "Vous avec un jeton d'accès personnel défini."
  rateLimitExceededRemoveToken: Supprimer le jeton
  rateLimitExceededGitHubPAT: "Jeton d'Accès Personnel GitHub"
  rateLimitExceededCopyPastePAT: Copiez et collez votre jeton
  rateLimitExceededSaveToken: Enregistrer le jeton
  errorTitle: "Une erreur s'est produite"
  errorIntro: "Une erreur s'est produite lors de la tentative d'obtention des derniers détails du statut."
  errorText: Vous pouvez réessayer dans quelques instants.
  errorHome: "Retourner sur la page d'accueil"
  pastScheduledMaintenance: Maintenance planifiée passée
  scheduledMaintenance: Maintenance planifiée
  scheduledMaintenanceSummaryStarted: Commencé le $DATE pour $DURATION minutes
  scheduledMaintenanceSummaryStarts: Commence le $DATE pour $DURATION minutes
  startedAt: Commencé le
  startsAt: Commence le
  duration: Durée
  durationMin: $DURATION minutes
  incidentCompleted: Terminé
  incidentScheduled: Planifié
  duration7D: 7j
  duration30D: 30j
  duration1Y: 1a
  durationAll: max
  status: Statut
  history: Historique
  uptime: Disponibilité
  responseTime: Temps de réponse
  responseTimeDay: Temps de réponse sur 24 heures
  responseTimeWeek: Temps de réponse sur 7 jours
  responseTimeMonth: Temps de réponse sur 30 jours
  responseTimeYear: Temps de réponse sur 1 an
  uptimeDay: Disponibilité sur 24 heures
  uptimeWeek: Disponibilité sur 7 jours
  uptimeMonth: Disponibilité sur 30 jours
  uptimeYear: Disponibilité sur 1 an
  degradedPerformance: 🟨 Performances dégradées
  completeOutage: 🟥 Panne totale
  partialOutage: 🟧 Panne partielle

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/15 * * * *"
